---
- name: Configure DNS for the AWX node
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ given_record | default(student + '.awx.' + ec2_name_prefix|lower + '.' + workshop_dns_zone) }}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
    wait: true
  delegate_to: localhost
