---

- name: reload systemctl
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    daemon_reload: true
    scope: "{{ systemd_scope }}"

- name: Create the Pod
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  shell: podman play kube /etc/containers/pods/awx.yaml
  listen: "restart service"

- name: restart service
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ service_name }}"
    scope: "{{ systemd_scope }}"
    state: restarted
    enabled: true
  listen: "restart service"
